Added skeleton for GUI.
MatasV/TraitsExpanded pull request #7
Opened 2020-04-26 10:29 UTC by Eskalior

- added required c# classes with minimal content
- added xml file containing dummy elements for the trait selection window
- added rule to build 
- added main menu option for testing the window

2020-04-26 20:32 UTC, ghost requested changes
looks good other than the inconsistent tabs vs spaces

2020-04-26 20:32 UTC, tyadams commented on TraitsExpanded/GUI/TraitSelectionGauntletScreen.cs
> +		private GauntletLayer _gauntletLayer;
please convert tabs to spaces

2020-04-28 14:47 UTC, MatasV commented
Looks good other than the extra spaces in a couple of lines

2020-04-28 14:56 UTC, MatasV approved these changes
I don't think a couple of tabs is a showstopper. He'll change it on the next iteration

2020-05-04 08:20 UTC, merged